version: '3.1'

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    command: ["postgres", "-c", "log_statement=all", "-c", "logging_collector=on", "-c", "log_directory=/var/log/postgresql"]
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/logs:/var/log/postgresql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      - DB_ADDRESS=postgresql://postgres:example@db:5432/database
    ports:
      - 4000:4000
    restart: always
volumes:
  postgres_data:
  postgres_logs:
